---
- name: create user or make sure it is present
  user:
    name="{{ item.name }}"
    shell=/bin/bash
    system=yes
    state=present
    createhome=yes
  with_items: "{{ ssh_users }}"
  no_log: True

- name: Add ssh user keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: "{{ ssh_users }}"
  no_log: True
